// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzOFd9kRUWIzlLgGfeRG9Q0WKC7pFUBdU',
    appId: '1:671220433895:web:961a7a3392d628d2cc7342',
    messagingSenderId: '671220433895',
    projectId: 'todotest-fl',
    authDomain: 'todotest-fl.firebaseapp.com',
    storageBucket: 'todotest-fl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdS0aNCegJpTtfmJirY5ppN43bRJt1_Q4',
    appId: '1:671220433895:android:593a5f3cdde24a80cc7342',
    messagingSenderId: '671220433895',
    projectId: 'todotest-fl',
    storageBucket: 'todotest-fl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_t1K2_g1WxozdgXkBwJRuVH0CVRSRXnI',
    appId: '1:671220433895:ios:4fd0b72226d2078ecc7342',
    messagingSenderId: '671220433895',
    projectId: 'todotest-fl',
    storageBucket: 'todotest-fl.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_t1K2_g1WxozdgXkBwJRuVH0CVRSRXnI',
    appId: '1:671220433895:ios:4fd0b72226d2078ecc7342',
    messagingSenderId: '671220433895',
    projectId: 'todotest-fl',
    storageBucket: 'todotest-fl.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzOFd9kRUWIzlLgGfeRG9Q0WKC7pFUBdU',
    appId: '1:671220433895:web:5aafe1c949be6025cc7342',
    messagingSenderId: '671220433895',
    projectId: 'todotest-fl',
    authDomain: 'todotest-fl.firebaseapp.com',
    storageBucket: 'todotest-fl.firebasestorage.app',
  );
}
